In [1]:
from google.cloud import bigquery
import pandas as pd
import numpy as np
import plotly.express as px
from itables import init_notebook_mode, show

client = bigquery.Client()

In [2]:
query = """
    SELECT *
    FROM `tz-data-dev.japan_occto_bronze.interconnectors`
"""

# Run the query
query_job = client.query(query)

# Convert the result to a pandas DataFrame
df = query_job.to_dataframe()

Forbidden: 403 POST https://bigquery.googleapis.com/bigquery/v2/projects/tz-analysis-compute/jobs?prettyPrint=false: Access Denied: Project tz-analysis-compute: User does not have bigquery.jobs.create permission in project tz-analysis-compute.

Location: None
Job ID: 1caab2bb-cba6-43b4-803f-90ea19c2dad6

In [36]:
# Convert datetime and resample to hourly
df['datetime_utc'] = pd.to_datetime(df['datetime_utc'])
df_hourly = df.set_index('datetime_utc').groupby('sortedZoneKeys').resample('H')['netFlow'].mean().reset_index()

# Filter to specific date range
start_date = '2024-05-31 15:00:00+00:00'
end_date = '2025-05-31 14:00:00+00:00'
df_hourly = df_hourly[(df_hourly['datetime_utc'] >= start_date) & (df_hourly['datetime_utc'] <= end_date)]

df_hourly.to_csv('JPN_IC_hourly.csv', index=False)
df_hourly

C:\Users\jy\AppData\Local\Temp\ipykernel_6028\2445995961.py:3: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df_hourly = df.set_index('datetime_utc').groupby('sortedZoneKeys').resample('H')['netFlow'].mean().reset_index()

      sortedZoneKeys              datetime_utc  netFlow
0       JP-CB->JP-HR 2024-05-31 15:00:00+00:00  -3023.0
1       JP-CB->JP-HR 2024-05-31 16:00:00+00:00  -3436.0
2       JP-CB->JP-HR 2024-05-31 17:00:00+00:00  -2442.5
3       JP-CB->JP-HR 2024-05-31 18:00:00+00:00  -3294.5
4       JP-CB->JP-HR 2024-05-31 19:00:00+00:00  -3556.5
...              ...                       ...      ...
96244   JP-TH->JP-TK 2025-05-31 10:00:00+00:00  23515.5
96245   JP-TH->JP-TK 2025-05-31 11:00:00+00:00  24689.0
96246   JP-TH->JP-TK 2025-05-31 12:00:00+00:00  24709.0
96247   JP-TH->JP-TK 2025-05-31 13:00:00+00:00  22818.0
96248   JP-TH->JP-TK 2025-05-31 14:00:00+00:00  21188.0

[87600 rows x 3 columns]

In [35]:
df

,datetime_utc,sortedZoneKeys,netFlow,ingestion_dt,datetime_local,week,month,year,day_of_month,day_of_week,within_day_half_hour,cumulative_half_hour,write_dt
0,2024-05-31 15:30:00+00:00,JP-CB->JP-HR,-3023.0,2025-06-24 19:40:05+00:00,2024-06-01 00:30:00,21,6,2024,1,6,2,7298,2025-07-11 08:55:16.840008+00:00
1,2024-05-31 15:30:00+00:00,JP-CB->JP-KN,-11388.0,2025-06-24 19:40:05+00:00,2024-06-01 00:30:00,21,6,2024,1,6,2,7298,2025-07-11 08:55:16.840008+00:00
2,2024-05-31 15:30:00+00:00,JP-CB->JP-TK,5517.0,2025-06-24 19:40:05+00:00,2024-06-01 00:30:00,21,6,2024,1,6,2,7298,2025-07-11 08:55:16.840008+00:00
3,2024-05-31 15:30:00+00:00,JP-CG->JP-KN,-392.0,2025-06-24 19:40:05+00:00,2024-06-01 00:30:00,21,6,2024,1,6,2,7298,2025-07-11 08:55:16.840008+00:00
4,2024-05-31 15:30:00+00:00,JP-CG->JP-KY,-5272.0,2025-06-24 19:40:05+00:00,2024-06-01 00:30:00,21,6,2024,1,6,2,7298,2025-07-11 08:55:16.840008+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
194395,2025-07-10 15:00:00+00:00,JP-CG->JP-SK,3870.0,2025-07-11 00:00:15+00:00,2025-07-11 00:00:00,27,7,2025,11,5,1,9169,2025-07-11 08:55:16.840008+00:00
194396,2025-07-10 15:00:00+00:00,JP-HKD->JP-TH,3507.0,2025-07-11 00:00:15+00:00,2025-07-11 00:00:00,27,7,2025,11,5,1,9169,2025-07-11 08:55:16.840008+00:00
194397,2025-07-10 15:00:00+00:00,JP-HR->JP-KN,3236.0,2025-07-11 00:00:15+00:00,2025-07-11 00:00:00,27,7,2025,11,5,1,9169,2025-07-11 08:55:16.840008+00:00
194398,2025-07-10 15:00:00+00:00,JP-KN->JP-SK,-434.0,2025-07-11 00:00:15+00:00,2025-07-11 00:00:00,27,7,2025,11,5,1,9169,2025-07-11 08:55:16.840008+00:00
194399,2025-07-10 15:00:00+00:00,JP-TH->JP-TK,30878.0,2025-07-11 00:00:15+00:00,2025-07-11 00:00:00,27,7,2025,11,5,1,9169,2025-07-11 08:55:16.840008+00:00

In [34]:
df_hourly = df.set_index('datetime_utc').groupby('sortedZoneKeys').resample('H')['netFlow'].mean().reset_index()
df_hourly.to_csv('JPN_IC_hourly.csv', index=False)

C:\Users\jy\AppData\Local\Temp\ipykernel_6028\3742053383.py:1: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df_hourly = df.set_index('datetime_utc').groupby('sortedZoneKeys').resample('H')['netFlow'].mean().reset_index()

In [33]:
df_hourly.groupby(['sortedZoneKeys', 'datetime_utc']).sum()

                                          netFlow
sortedZoneKeys datetime_utc
JP-CB->JP-HR   2024-05-31 15:00:00+00:00  -3023.0
               2024-05-31 16:00:00+00:00  -3436.0
               2024-05-31 17:00:00+00:00  -2442.5
               2024-05-31 18:00:00+00:00  -3294.5
               2024-05-31 19:00:00+00:00  -3556.5
...                                           ...
JP-TH->JP-TK   2025-07-10 11:00:00+00:00  29989.0
               2025-07-10 12:00:00+00:00  31174.0
               2025-07-10 13:00:00+00:00  31445.0
               2025-07-10 14:00:00+00:00  30901.0
               2025-07-10 15:00:00+00:00  30878.0

[97210 rows x 1 columns]