In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import xarray as xr
import pypsa
import xlsxwriter
import tz_pypsa
import tz_pypsa.wrangle as wrangle
import pandas as pd
# import tz_solve
import plotly.express as px
import plotly.graph_objects as go
from tz_pypsa.model import Model
from tz_pypsa.utils import get_examples

In [3]:
n = pypsa.Network()
n.import_from_netcdf("G:/Shared drives/Analysis/01 Projects/2024/Google 24 7 CFE/04. Japan/02. Data & Results/Outputs/Brownfield/Tableau/nc_files/reference_run_13-05-2025.nc")

INFO:pypsa.io:Imported network reference_run_13-05-2025.nc has buses, carriers, generators, links, loads, storage_units

In [4]:
hourly_df = wrangle.transform_visualiser_hourly_output(n)

Please enter the market/country/region for this Pypsa run.
Examples: 'ASEAN, Japan, Taiwan, Indonesia, etc'
You entered: Japan
Please enter the run identifier.
Examples: '1, first-run, run-with-policy-constraint, etc'
You entered: Testing

In [5]:
yearly_df = wrangle.transform_visualiser_yearly_output(n)

Please enter the market/country/region for this Pypsa run.
Examples: 'ASEAN, Japan, Taiwan, Indonesia, etc'
You entered: Japan
Please enter the run identifier.
Examples: '1, first-run, run-with-policy-constraint, etc'
You entered: Testing

In [7]:
n.generators_t.p

Generator,JPN01-Biomass-2023active_exo,JPN01-Biomass-2030_endo,JPN01-Biomass-2030_exo,JPN01-BlueH2-2030_endo,JPN01-BlueH2-2030_exo,JPN01-BlueH2_Gas-2030_endo,JPN01-BlueH2_Gas-2030_exo,JPN01-BlueNH3-2030_endo,JPN01-BlueNH3-2030_exo,JPN01-BlueNH3_Coal-2030_endo,...,JPN09-OffshoreWind-2030_exo,JPN09-Oil-2023active_exo,JPN09-Oil-2030_endo,JPN09-Oil-2030_exo,JPN09-OnshoreWind-2023active_exo,JPN09-OnshoreWind-2030_endo,JPN09-OnshoreWind-2030_exo,JPN09-SolarGrid-2023active_exo,JPN09-SolarGrid-2030_endo,JPN09-SolarGrid-2030_exo
snapshot,,,,,,,,,,,,,,,,,,,,,
2030-01-01 00:00:00,76.38013,0.0,360.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,27.531,0.0,0.0,0.0,162.93474,29.797157,59.594314,0.0,0.0,0.0
2030-01-01 01:00:00,419.39000,0.0,360.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.051,0.0,0.0,0.0,163.56627,29.912650,59.825300,0.0,0.0,0.0
2030-01-01 02:00:00,419.39000,0.0,360.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.933,0.0,0.0,0.0,166.09239,30.374621,60.749243,0.0,0.0,0.0
2030-01-01 03:00:00,419.39000,0.0,360.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.185,0.0,0.0,0.0,164.82933,30.143636,60.287271,0.0,0.0,0.0
2030-01-01 04:00:00,419.39000,0.0,360.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.185,0.0,0.0,0.0,166.72392,30.490114,60.980229,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2030-12-31 19:00:00,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,341.734,0.0,0.0,0.0,266.50566,48.737986,97.475971,0.0,0.0,0.0
2030-12-31 20:00:00,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,344.793,0.0,0.0,0.0,238.71834,43.656300,87.312600,0.0,0.0,0.0
2030-12-31 21:00:00,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,330.372,0.0,0.0,0.0,224.82468,41.115457,82.230914,0.0,0.0,0.0
2030-12-31 22:00:00,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,307.211,0.0,0.0,0.0,219.77244,40.191514,80.383029,0.0,0.0,0.0
2030-12-31 23:00:00,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,265.259,0.0,0.0,0.0,213.45714,39.036586,78.073171,0.0,0.0,0.0

In [8]:
n.generators

,bus,control,type,p_nom,p_nom_mod,p_nom_extendable,p_nom_min,p_nom_max,p_min_pu,p_max_pu,...,ramp_limit_down,ramp_limit_start_up,ramp_limit_shut_down,weight,p_nom_opt,min_utilisation_rate,technology,generation_blend_share,is_blend_or_ccs,max_utilisation_rate
Generator,,,,,,,,,,,,,,,,,,,,,
JPN01-Coal-2023active_exo,JPN01,PQ,coal-unspecified,1929.81,0.0,False,0.0,1929.81,0.0,1.0,...,0.6,1.0,1.0,1.0,1929.81,0.00,coal-unspecified,0.0,False,0.57
JPN01-Coal-2030_endo,JPN01,PQ,coal-unspecified,0.00,0.0,True,0.0,0.00,0.0,1.0,...,0.6,1.0,1.0,1.0,0.00,0.00,coal-unspecified,0.0,False,0.57
JPN01-Coal-2030_exo,JPN01,PQ,coal-unspecified,0.00,0.0,False,0.0,0.00,0.0,1.0,...,0.6,1.0,1.0,1.0,0.00,0.00,coal-unspecified,0.0,False,0.57
JPN01-Gas-2023active_exo,JPN01,PQ,gas-unspecified,426.98,0.0,False,0.0,426.98,0.0,1.0,...,1.0,1.0,1.0,1.0,426.98,0.13,gas-unspecified,0.0,False,0.56
JPN01-Gas-2030_endo,JPN01,PQ,gas-unspecified,0.00,0.0,True,0.0,173.55,0.0,1.0,...,1.0,1.0,1.0,1.0,0.00,0.13,gas-unspecified,0.0,False,0.56
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
JPN09-GasCCSSequestered-2030_endo,JPN09,PQ,gas-CCS-unspecified,0.00,0.0,True,0.0,0.00,0.0,1.0,...,1.0,1.0,1.0,1.0,0.00,0.00,gas-CCS-unspecified,0.7,True,1.00
JPN09-GreenH2-2030_endo,JPN09,PQ,blending-greenH2-gas-unspecified,0.00,0.0,True,0.0,0.00,0.0,1.0,...,1.0,1.0,1.0,1.0,0.00,0.00,blending-greenH2-gas-unspecified,0.1,True,1.00
JPN09-GreenH2_Gas-2030_endo,JPN09,PQ,blending-greenH2-gas-unspecified,0.00,0.0,True,0.0,0.00,0.0,1.0,...,1.0,1.0,1.0,1.0,0.00,0.00,blending-greenH2-gas-unspecified,0.9,True,1.00
JPN09-GreenNH3-2030_endo,JPN09,PQ,blending-greenNH3-coal-unspecified,0.00,0.0,True,0.0,0.00,0.0,1.0,...,1.0,1.0,1.0,1.0,0.00,0.00,blending-greenNH3-coal-unspecified,0.2,True,1.00
JPN09-GreenNH3_Coal-2030_endo,JPN09,PQ,blending-greenNH3-coal-unspecified,0.00,0.0,True,0.0,0.00,0.0,1.0,...,1.0,1.0,1.0,1.0,0.00,0.00,blending-greenNH3-coal-unspecified,0.8,True,1.00

In [6]:
hourly_df

,snapshot,Node,Tech,Value,Type,Node_Destination,HourOfDay,DayOfMonth,Month,Year,Market,Pypsa_Run_Id,Hour8760,long_name
0,2030-01-01 00:00:00,JPN01,biomass-unspecified,0.559900,CapacityFactor,NaN,0,1,1,2030,Japan,Testing,0,Hokkaido
1,2030-01-01 00:00:00,JPN01,blending-blueH2-gas-unspecified,NaN,CapacityFactor,NaN,0,1,1,2030,Japan,Testing,0,Hokkaido
2,2030-01-01 00:00:00,JPN01,blending-blueNH3-coal-unspecified,0.000000,CapacityFactor,NaN,0,1,1,2030,Japan,Testing,0,Hokkaido
3,2030-01-01 00:00:00,JPN01,blending-greenH2-gas-unspecified,NaN,CapacityFactor,NaN,0,1,1,2030,Japan,Testing,0,Hokkaido
4,2030-01-01 00:00:00,JPN01,blending-greenNH3-coal-unspecified,NaN,CapacityFactor,NaN,0,1,1,2030,Japan,Testing,0,Hokkaido
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3092275,2030-12-31 23:00:00,JPN09,Interconnector,-0.000000,Interconnector,JPN07,23,31,12,2030,Japan,Testing,8759,Kyushu
3092276,2030-12-31 23:00:00,JPN09,NaN,63.290000,Price,NaN,23,31,12,2030,Japan,Testing,8759,Kyushu
3092277,2030-12-31 23:00:00,JPN09,NaN,10350.073103,ResidualDemand,NaN,23,31,12,2030,Japan,Testing,8759,Kyushu
3092278,2030-12-31 23:00:00,JPN09,Batteries,587.901093,Storage,NaN,23,31,12,2030,Japan,Testing,8759,Kyushu
3092279,2030-12-31 23:00:00,JPN09,PumpedHydro,2172.812010,Storage,NaN,23,31,12,2030,Japan,Testing,8759,Kyushu

In [5]:
yearly_df.to_csv('japan_brownfield_yearly_008.csv', index=False)

In [6]:
hourly_df.to_csv('japan_brownfield_hourly_008.csv', index=False)