In [1]:
import pypsa
import pandas as pd

In [3]:
p_min_pu = pd.read_csv("/home/jy/tz-amp/.amp/client-earth_CE-A-OCCTO-003_testing-v5/templates/power_limit_lower.csv")

In [19]:
p_max_pu = pd.read_csv("/home/jy/tz-amp/.amp/client-earth_CE-A-OCCTO-003_testing-v5/templates/capacity_factor.csv")
df_cf = p_max_pu.copy()

In [21]:
p_max_pu.loc[p_max_pu.technology == 'coal-unspecified']

Empty DataFrame
Columns: [year_part, day_part, node, node_name, node_group, interconnector, interconnector_name, technology, technology_group, default_data, user_data]
Index: []

In [15]:
p_max_pu_v1 = pd.read_csv("/home/jy/tz-amp/.amp/client-earth_CE-A-OCCTO-002_v60/templates/capacity_factor.csv")

In [5]:
p_min_pu.loc[p_min_pu.technology == 'nuclear', 'user_data'] = 0.585
p_min_pu.loc[(p_min_pu.technology == 'coal-unspecified') & (p_min_pu.node == 'GRIDREGION-JPN-TK'), 'user_data'] = 0.20
p_min_pu.loc[(p_min_pu.technology == 'coal-unspecified') & (p_min_pu.node == 'GRIDREGION-JPN-CB'), 'user_data'] = 0.20
p_min_pu.loc[(p_min_pu.technology == 'coal-unspecified') & (p_min_pu.node == 'GRIDREGION-JPN-HR'), 'user_data'] = 0.20
p_min_pu.loc[(p_min_pu.technology == 'coal-unspecified') & (p_min_pu.node == 'GRIDREGION-JPN-KA'), 'user_data'] = 0.20
p_min_pu.loc[(p_min_pu.technology == 'coal-unspecified') & (p_min_pu.node == 'GRIDREGION-JPN-CG'), 'user_data'] = 0.20
p_min_pu.loc[(p_min_pu.technology == 'coal-unspecified') & (p_min_pu.node == 'GRIDREGION-JPN-SH'), 'user_data'] = 0.20
p_min_pu.loc[(p_min_pu.technology == 'coal-unspecified') & (p_min_pu.node == 'GRIDREGION-JPN-KY'), 'user_data'] = 0.20

In [6]:
p_max_pu.loc[(p_max_pu.technology == 'coal-unspecified') & (p_max_pu.node == 'GRIDREGION-JPN-HK'), 'user_data'] = 0.46
p_max_pu.loc[(p_max_pu.technology == 'coal-unspecified') & (p_max_pu.node == 'GRIDREGION-JPN-TH'), 'user_data'] = 0.57
p_max_pu.loc[(p_max_pu.technology == 'coal-unspecified') & (p_max_pu.node == 'GRIDREGION-JPN-TK'), 'user_data'] = 0.62
p_max_pu.loc[(p_max_pu.technology == 'coal-unspecified') & (p_max_pu.node == 'GRIDREGION-JPN-CB'), 'user_data'] = 0.63
p_max_pu.loc[(p_max_pu.technology == 'coal-unspecified') & (p_max_pu.node == 'GRIDREGION-JPN-HR'), 'user_data'] = 0.60
p_max_pu.loc[(p_max_pu.technology == 'coal-unspecified') & (p_max_pu.node == 'GRIDREGION-JPN-KA'), 'user_data'] = 0.60
p_max_pu.loc[(p_max_pu.technology == 'coal-unspecified') & (p_max_pu.node == 'GRIDREGION-JPN-CG'), 'user_data'] = 0.52
p_max_pu.loc[(p_max_pu.technology == 'coal-unspecified') & (p_max_pu.node == 'GRIDREGION-JPN-SH'), 'user_data'] = 0.59
p_max_pu.loc[(p_max_pu.technology == 'coal-unspecified') & (p_max_pu.node == 'GRIDREGION-JPN-KY'), 'user_data'] = 0.51

In [7]:
df_cf = df_cf.loc[(df_cf['technology'] == 'hydro-reservoir-and-run-of-river') | (df_cf['technology'] == 'geothermal-unspecified') | (df_cf['technology'] == 'biomass')]
df_cf = df_cf.drop(columns=['user_data']).rename(columns={'default_data': 'user_data'})

In [8]:
p_min_pu = p_min_pu.set_index(['year_part', 'day_part', 'node','technology'])
df_cf = df_cf.set_index(['year_part', 'day_part', 'node','technology'])

p_min_pu.update(df_cf, overwrite=False)  # only fills NaN
p_min_pu = p_min_pu.reset_index()

In [ ]:
p_max_pu

,year_part,day_part,node,node_name,node_group,interconnector,interconnector_name,technology,technology_group,default_data,user_data
0,jul09,06h00-07h00-utc,GRIDREGION-JPN-SH,Shikoku,NaN,NaN,NaN,wind-onshore,NaN,0.17,NaN
1,jul09,06h00-07h00-utc,GRIDREGION-JPN-SH,Shikoku,NaN,NaN,NaN,photovoltaic-unspecified,NaN,0.10,NaN
2,jul09,06h00-07h00-utc,GRIDREGION-JPN-SH,Shikoku,NaN,NaN,NaN,biomass,NaN,0.80,NaN
3,jul09,06h00-07h00-utc,GRIDREGION-JPN-SH,Shikoku,NaN,NaN,NaN,geothermal-unspecified,NaN,0.00,NaN
4,jul09,06h00-07h00-utc,GRIDREGION-JPN-SH,Shikoku,NaN,NaN,NaN,wind-offshore-unspecified,NaN,0.26,NaN
...,...,...,...,...,...,...,...,...,...,...,...
551875,nov20,14h00-15h00-utc,GRIDREGION-JPN-KY,Kyushu,NaN,NaN,NaN,biomass,NaN,0.81,NaN
551876,nov20,14h00-15h00-utc,GRIDREGION-JPN-KY,Kyushu,NaN,NaN,NaN,geothermal-unspecified,NaN,0.77,NaN
551877,nov20,14h00-15h00-utc,GRIDREGION-JPN-KY,Kyushu,NaN,NaN,NaN,wind-offshore-unspecified,NaN,0.22,NaN
551878,nov20,14h00-15h00-utc,GRIDREGION-JPN-KY,Kyushu,NaN,NaN,NaN,hydro-pumped-storage-unspecified,NaN,1.00,NaN
551879,nov20,14h00-15h00-utc,GRIDREGION-JPN-KY,Kyushu,NaN,NaN,NaN,hydro-reservoir-and-run-of-river,NaN,0.11,NaN

In [18]:
df = pd.read_csv("/home/jy/tz-amp/.amp/client-earth_CE-A-OCCTO-003_v3/templates/state_of_charge_set.csv")

In [19]:
df['year_part'] = df['year_part'].str.lower()

In [20]:
df.to_csv("/home/jy/tz-amp/.amp/client-earth_CE-A-OCCTO-003_v3/templates/state_of_charge_set.csv", index=False)

In [17]:
p_min_pu.to_csv("/home/jy/tz-amp/.amp/client-earth_CE-A-OCCTO-003_testing-v5/templates/power_limit_lower.csv", index=False)
p_max_pu.to_csv("/home/jy/tz-amp/.amp/client-earth_CE-A-OCCTO-003_testing-v5/templates/capacity_factor.csv", index=False)

In [ ]:
def convert_to_datetime_index(df: pd.DataFrame, year: int = 2040) -> pd.DataFrame:
    """
    Convert year_part (e.g., 'jul09') and day_part (e.g., '06h00-07h00-utc') to datetime index.
    
    Parameters:
    -----------
    df : pd.DataFrame
        DataFrame with 'year_part' and 'day_part' columns
    year : int
        The year to use for the datetime index
    
    Returns:
    --------
    pd.DataFrame with datetime index
    """
    df = df.copy()
    
    # Parse year_part: 'jul09' -> 'Jul 09' -> datetime
    # Convert to proper date string format
    year_part_dates = pd.to_datetime(
        df['year_part'].str.capitalize() + f' {year}',
        format='%b%d %Y'
    )
    
    # Parse day_part: '06h00-07h00-utc' -> extract start hour (06:00)
    # Extract the first time component before the '-'
    time_str = df['day_part'].str.split('-').str[0]  # Gets '06h00'
    hours = time_str.str.extract(r'(\d+)h')[0].astype(int)
    minutes = time_str.str.extract(r'h(\d+)')[0].astype(int)
    
    # Combine date and time
    df.index = year_part_dates + pd.to_timedelta(hours, unit='h') + pd.to_timedelta(minutes, unit='m')
    
    return df

In [ ]:
df = convert_to_datetime_index(df)

In [ ]:
df['weekday'] = df.index.dayofweek
df['hour'] = df.index.hour

In [ ]:
df.to_csv("251118_SOC_Input.csv")

In [ ]:
df

In [ ]:
df = calculate_curtailment(n)

In [ ]:
df = calculate_capacity_factor(n)

In [ ]:
df = calculate_emissions(n)

In [ ]:
df

In [ ]:
df['capacity_factor_link']